config/routes.rb
FileCabinet::Application.routes.draw do
  devise_for :users
  get "welcome/index"
  resources :docs
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/doc.rb
class Doc < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5}
	validates :body, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :find_docs, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :create, :delete]

	def index
		@docs = Doc.all.order("created_at DESC")
	end

	def new
		 @doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(docs_params)
		if @doc.save
			flash[:sucess] = "Document is saved"
			redirect_to  @doc
		else
		  flash[:error]	= "Could not save document"
		  render "new"
		end  
	end



  def show
  end	

  def edit
  end

  def update
   if @doc.update(docs_params)
   	redirect_to @doc
   else
   	render "edit"
   end	
  end

	private
	def find_docs
		@doc = Doc.find(params[:id])
	end	
	def docs_params
	  params.require(:doc).permit(:title, :body)
	end

end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<div class ="col-md-8 col-md-offset-2 doc-header">
  <h3>New Story</h3>
  <%= form_for @doc do |f| %>
    <% if @doc.errors.any? %>
      <div class="errors">
        <h4>Please review the problems below:</h4>
        <ul>
          <% @doc.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>  
    <% end %> 

    <div class ="form-group" >
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class ="form-group" >
      <%= f.label :body %>
      <%= f.text_area :body, :class => "form-control article-text-area" %>
    </div>
    <div class ="form-group" >
      <%= f.button :submit, :class => "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/docs/edit.html.erb
<div class ="col-md-8 col-md-offset-2 doc-header">
  <h3>Edit Story</h3>
  <%= form_for @doc do |f| %>
    <% if @doc.errors.any? %>
      <div class="errors">
        <h4>Please review the problems below:</h4>
        <ul>
          <% @doc.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>  
    <% end %> 
    <div class ="form-group" >
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class ="form-group" >
      <%= f.label :body %>
      <%= f.text_area :body, :class => "form-control article-text-area" %>
    </div>
    <div class ="form-group" >
      <%= f.button :submit, :class => "btn btn-info" %>
    </div>
  <% end %>
   <%= link_to "Back", :back %>
</div>

app/views/docs/index.html.erb
<div class ="col-md-8 col-md-offset-2 doc-header">
  <h3>Stories</h3>
	<% @docs.each do |doc| %>
		 <%= link_to doc.title, doc_path(doc) %></br>
		 <%= truncate(doc.body, length:50) %></br>
	<% end %></br>
	<%= link_to "Create Doc", new_doc_path %>
</div>

app/views/docs/new.html.erb
<%= render "form" %>

app/views/docs/show.html.erb
<div class ="col-md-8 col-md-offset-2 doc-header">
  <h2><%= @doc.title %></h2></br>
  <div class ="show-doc" >
  <%= @doc.body %></br>
  </div>
  <div class ="show-doc" >
    <%= link_to "Edit Story", edit_doc_path(@doc), {:style => "margin-top: 5% "} %></br>
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileCabinet</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="/">FileCabinet</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li class=""><a href="#"></a></li>
	      <li><a href="#"></a></li>
	      <li><a href="#"></a></li> 
	      <li><a href="#"></a></li> 
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	      <% if user_signed_in? %>
			    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-menu-right" role="menu">
			     <li a href="#"><%= link_to('Edit Profile', edit_user_registration_path) %></li>
			     <li a href="#"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
	      <% else %>
	        <li><%= link_to "Sign Up", new_user_registration_path %></li>
	        <li><%= link_to "Login", user_session_path %></li>
        <% end %>
      </ul>
	  </div>
	</nav>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>